on:
  push:
     branches:
       - main
       
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 17 * * *'      

name: buildpdf

jobs:
  buildpdf:
    name: Build-PDF
    runs-on: macOS-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Install R
        uses: r-lib/actions/setup-r@v1
      
      - name: Install pandoc
        uses: r-lib/actions/setup-pandoc@v1

      - name: Install TinyTeX
        uses: r-lib/actions/setup-tinytex@v1
      
      - name: Install R packages
        run: Rscript -e 'install.packages(c("rmarkdown", "pagedown", "tidyverse", "iprior", "here", "gganimate"))'      
        
      - name: Build PDF CV
        run: Rscript -e 'pagedown::chrome_print(rmarkdown::render("index.Rmd", params = list(pdf_mode = TRUE)))'

      - name: Build HTML CV
        run: Rscript -e 'rmarkdown::render("index.Rmd", output_dir = "site", outparams = list(pdf_mode = FALSE))'

      - name: Move PDF and CSS folder
        run: |
          mv -f css/ site/css/
          mv -f index.pdf site_/haziq_cv.pdf

      - name: Upload site folder
        uses: actions/upload-artifact@v2
        with:
          name: haziq_cv
          path: site/

  checkdep:
    name: Checkout-and-Deploy
    runs-on: ubuntu-latest
    needs: buildpdf

    steps:
      - name: Download site folder
        uses: actions/download-artifact@v2
        with:
          name: haziq_cv     

      - name: Deploy to gh-pages branch
        uses: Cecilapp/GitHub-Pages-deploy@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          email: haziq.jamil@ubd.edu.bn  
          build_dir: .
          branch: gh-pages

      - uses: dsaltares/fetch-gh-release-asset@master
        with:
          repo: haziqj/stat-tables
          file: stat-tables.pdf
          target: stat-tables.pdf
          token: ${{ secrets.GITHUB_TOKEN }}          
          