on:
  push:
     branches:
       - main

# on:
#   schedule:
#     # * is a special character in YAML so you have to quote this string
#     - cron:  '0 17 * * *'      

name: buildpdf

jobs:
  buildpdf:
    name: Build-PDF
    runs-on: macOS-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Install R
        uses: r-lib/actions/setup-r@v1
      
      - name: Install pandoc
        uses: r-lib/actions/setup-pandoc@v1

      - name: Install TinyTeX
        uses: r-lib/actions/setup-tinytex@v1
      
      - name: Install R packages
        run: Rscript -e 'install.packages(c("rmarkdown", "pagedown", "tidyverse", "iprior", "here", "gganimate"))'      
        
      - name: Build PDF CV
        run: Rscript -e 'pagedown::chrome_print(rmarkdown::render("index.Rmd", params = list(pdf_mode = TRUE)))'

      - name: Rename PDF
        run: Rscript -e 'file.rename("index.pdf", "haziq_cv.pdf")'    

      - name: Upload PDF CV
        uses: actions/upload-artifact@v2
        with:
          name: haziq_cv_pdf
          path: haziq_cv.pdf

  checkdep:
    name: Checkout-and-Deploy
    runs-on: ubuntu-latest
    needs: buildpdf

    steps:
      - name: Download PDF CV
        uses: actions/download-artifact@v2
        with:
          name: haziq_cv_pdf       

      # - name: Put PDF CV in main folder
      #   uses: Cecilapp/GitHub-Pages-deploy@v3
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   with:
      #     email: haziq.jamil@ubd.edu.bn  
      #     build_dir: gh-pages
      #     branch: main

      - name: Put PDF CV in main folder
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .
          publish_branch: gh-pages
          cname: haziqj.ml
          allow_empty_commit: true
          keep_files: true

      - uses: dsaltares/fetch-gh-release-asset@master
        with:
          repo: haziqj/stat-tables
          file: stat-tables.pdf
          target: stat-tables.pdf
          token: ${{ secrets.GITHUB_TOKEN }}          
          