on:
  push:
     branches:
       - main
       
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 17 * * *'      

name: buildpdf

jobs:
  buildpdf:
    name: Build-PDF
    runs-on: macOS-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Install R
        uses: r-lib/actions/setup-r@v1
      
      - name: Install pandoc
        uses: r-lib/actions/setup-pandoc@v1
        with:
          pandoc-version: '2.14.2'

      - name: Install TinyTeX
        uses: r-lib/actions/setup-tinytex@v1

      - name: Install R packages
        env:
          GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}      
        run: |
          Rscript -e 'install.packages(c("rmarkdown", "remotes", "tidyverse", "iprior", "here", "gganimate", "gifski", "transformr"))'
          Rscript -e 'remotes::install_github("rstudio/pagedown", dependencies = TRUE)'

      - name: Build PDF CV
        run: Rscript -e 'pagedown::chrome_print(rmarkdown::render("index.Rmd", params = list(pdf_mode = TRUE)))'

      - name: Build HTML CV
        run: Rscript -e 'rmarkdown::render("index.Rmd", output_dir = "site", params = list(pdf_mode = FALSE))'

      - name: Build README
        run: Rscript -e 'writeLines(c(
                paste("Last rendered:", Sys.time(), Sys.timezone(), "\n"),
                "# pandoc version\n",
                "```", system("pandoc --version", intern = TRUE), "```\n",
                "# Session info\n",
                "```", capture.output(sessionInfo()), "```"
                ), file("README.md")
              )'

      - name: Move PDF, CSS folder and README
        run: |
          mv -f css/ site/css/
          mv -f haziq_cv.pdf site/haziq_cv.pdf
          mv -f README.md site/README.md

      - name: Upload site folder
        uses: actions/upload-artifact@v2
        with:
          name: haziq_cv
          path: site/

  checkdep:
    name: Checkout-and-Deploy
    runs-on: ubuntu-latest
    needs: buildpdf

    steps:
      - name: Download site folder
        uses: actions/download-artifact@v2
        with:
          name: haziq_cv     

      - name: Deploy to gh-pages branch
        uses: Cecilapp/GitHub-Pages-deploy@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          email: haziq.jamil@ubd.edu.bn  
          build_dir: .
          branch: gh-pages

      - uses: dsaltares/fetch-gh-release-asset@master
        with:
          repo: haziqj/stat-tables
          file: stat-tables.pdf
          target: stat-tables.pdf
          token: ${{ secrets.GITHUB_TOKEN }}          
          